# Config file for automatic testing at travis-ci.org

language: python
python:
    - 3.8
    - 3.7
stages:
    - Black
install: &requirements
    - pip install -r requirements.txt
    - pip install tox-travis
script: tox
after_success: codecov
jobs:
    include:
        - stage: Black
          install: *requirements
          script:
              - tox -e black
